config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  devise_for :users
  # get 'rooms/index'
  resources :rooms
  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name

    after_create_commit { broadcast_append_to "rooms" }
    
    has_many :room_messages, dependent: :destroy, inverse_of: :room
    has_many :users, through: :users_in_room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user
  after_create_commit do
    notify_recipients
    broadcast_append_to "room_messages" 
  end

  private 

  def notify_recipients
    # users_in_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, uniqueness: true, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_messages, dependent: :destroy

  has_many :users, through: :users_in_room

  has_many :notifications, as: :recipient, dependent: :destroy

  after_create_commit { broadcast_append_to "users" }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
    end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController

    def create
        @room = Room.find params.dig(:room_message, :room_id)
        @room_message = RoomMessage.create user: current_user,
                                           room: @room,
                                           message: params.dig(:room_message, :message)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @room = Room.new
    @users = User.all
  end

  def create 
    @room = Room.create(name: params["room"]["name"])
  end

  def show
    @rooms = Room.all
    @users = User.all
    @room = Room.find(params[:id]) if params[:id]
    @current_user = current_user
    @current_room = Room.find(params[:id]) 
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end 

  private

  def set_rooms_and_users 

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <style>
    <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
    }
    <%= ".mess-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end;
    }
  </style>

  <head>
    <title>Super</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: 'shared/nav_bar' %>
    <%= yield %>
  </body>
</html>

app/views/room_messages/_room_message.html.erb
<div class="room_message mess-<%= room_message.user.id %>">
  <div class="message-box msg-<%= room_message.user.id %> " >
      <h4 class="name"> 
        <%= room_message.user.username %> 
      </h4>
    <%= room_message.message %>
  </div>
</div>

app/views/rooms/_create_room_form.html.erb
<%= form_with model: @room do |f| %>
    <div class = "mb-3 ml-0 row">

        <%= f.submit "New room", class: 'btn btn-primary' %>

        <div class = "col-sm-10">
            <%= f.text_field :name, placeholder: "Name", class: 'form-control'%>
        </div>  
    </div>
    
<%end%>

app/views/rooms/_room.html.erb
<div> 
    <%= turbo_frame_tag RoomMessage.new %>
    <%= link_to room.name, room , data: {turbo_frame: dom_id(RoomMessage.new)} %>
</div>

app/views/rooms/index.html.erb
<div class="container" class = 'mt-3'>

    <h3 class = 'mt-3'> 
        Chats
    </h3>

    <%= render partial: "create_room_form" %>

    <h5 class = 'mt-3'> 
        Choose room 
    </h5>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms" class = "mt-3">
        <%= render @rooms %>
    </div>

    <h3 class="mt-3"> 
        Users 
    </h3>

    <%= turbo_stream_from "users" %>
    <div id="users">
        <%= render @users %>
    </div>    

</div>

app/views/rooms/show.html.erb
<%= turbo_frame_tag @room_message do %>
<h1>
  <%= @current_room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
  
    <div class="chat mt-3">

      <%= turbo_stream_from "room_messages"%>
      <div id="room_messages">
          <%= render @room_messages %>
      </div>
  
    </div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>

  </div>
</div>
<%end%>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
    <header class = "p-3 bg-dark text-white">
        <div class = "container">
            <nav class="d-flex flex-warp align-items-center justify-content-center justify-content-lg-start">
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                </ul>

                <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
                    <% if user_signed_in? %>
                        <li class = "dropdown">
                            <%= nav_tab current_user.name_or_email, '#', 
                                class: 'nav-link px-2 dropdown-toggle',
                                data: {"bs-toggle": 'dropdown'}, current_page: current_page %> 

                            <ul class = "dropdown-menu">


                                <li>
                                    <%= link_to 'Edit profile', edit_user_path(current_user), 
                                        class: 'dropdown-item'%>
                                </li>

                                <li><hr class = "dropdown-divider"></li>

                                <li>
                                    <%= link_to 'Log Out', session_path, 
                                        class: 'dropdown-item', data: {method: :delete} %> 
                                </li>


                            </ul>
                        </li>
                        </div>
                    <% else %>
                        <li> <%= nav_tab 'Sign Up', new_user_path, 
                            class: 'nav-link px-2', current_page: current_page %> </li>
                        <li> <%= nav_tab 'Log In', new_session_path, 
                            class: 'nav-link px-2', current_page: current_page %> </li>                            
                    <% end %>        
                </ul>
            </nav>
        </div>
    </header>
  <% end %>

app/views/shared/_nav_bar.html.erb
<header class = "p-3 bg-dark text-white">
    <div class="container"> 
      <nav class="d-flex flex-warp align-items-center justify-content-center justify-content-lg-start">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>

            <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
            <% if user_signed_in? %>
              <%= link_to current_user.email, edit_user_registration_path, class: 'nav-link px-2' %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link px-2' %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link px-2' %>
              <%= link_to "Login", new_user_session_path, class: 'nav-link px-2' %>
            <% end %>
          </ul>
        </nav>
    </div>
</header>

app/views/users/_user.html.erb
<div> <%= link_to user.username, edit_user_registration_path %> </div>